version: '3.8'

services:
  db:
    image: postgres:16
    container_name: cricket_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"  # Port mapping using .env variable for flexibility
    volumes:
      - ./data/03_db:/var/lib/postgresql/data
